-- MySQL Script generated by MySQL Workbench
-- Sat May 16 12:34:51 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema soma
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema soma
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `soma` DEFAULT CHARACTER SET utf8 ;
USE `soma` ;

-- -----------------------------------------------------
-- Table `Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `endereco` (
  `idEndereco` INT NOT NULL AUTO_INCREMENT,
  `numCep` INT(11) NOT NULL,
  `descLogradouro` VARCHAR(45) NOT NULL,
  `numLocal` VARCHAR(45) NOT NULL,
  `descComplemento` VARCHAR(45) NULL,
  `descBairro` VARCHAR(45) NULL,
  `descCidade` VARCHAR(45) NULL,
  `siglaUf` VARCHAR(2) NULL,
  PRIMARY KEY (`idEndereco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `descNome` VARCHAR(100) NOT NULL COMMENT 'Nome completo',
  `descEmail` VARCHAR(80) NOT NULL COMMENT 'Email de contato',
  `descSenha` VARCHAR(45) NULL,
  `descRg` VARCHAR(20) NULL COMMENT 'Registro Geral',
  `dataNascimento` DATE NULL COMMENT 'Data de nascimento',
  `flgSexo` VARCHAR(1) NULL DEFAULT 'M' COMMENT 'F -  Feminino\nM - Masculino',
  `flgTipoPessoa` VARCHAR(1) NULL DEFAULT 'F' COMMENT 'F - Física\nJ - Jurídica',
  `numCpf` INT(13) NOT NULL COMMENT 'CPF (sem formatação)',
  `numTelefone` INT(15) NULL COMMENT 'Telefone fixo (sem formatação)',
  `numWhatsapp` INT(15) NULL COMMENT 'Telefone Whatsapp (sem formatação)',
  `Endereco_idEndereco` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  CONSTRAINT `fk_Usuario_Endereco`
    FOREIGN KEY (`Endereco_idEndereco`)
    REFERENCES `endereco` (`idEndereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Usuario_Endereco_idx` ON `usuario` (`Endereco_idEndereco` ASC);


-- -----------------------------------------------------
-- Table `Vendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vendedor` (
  `idVendedor` INT NOT NULL AUTO_INCREMENT,
  `dataCadastro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `flgBanca` TINYINT(1) NOT NULL DEFAULT '1' COMMENT '0 - Não é banca\n1 - É banca',
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idVendedor`),
  CONSTRAINT `fk_Cliente_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Cliente_Usuario1_idx` ON `vendedor` (`Usuario_idUsuario` ASC);


-- -----------------------------------------------------
-- Table `Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `dataCadastro` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `flgLigacao` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '0 - Sem ligação\n1 - Realizar ligação',
  `descPagseguroId` VARCHAR(60) NULL,
  `flgFormaPagamento` TINYINT(1) NOT NULL DEFAULT '2' COMMENT '1 - Pagseguro\n2 - Boleto Paghiper',
  `flgPeriodicidadePagamento` TINYINT(1) NOT NULL DEFAULT '1' COMMENT '1 - Mensal\n2 - Anual',
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idCliente`),
  CONSTRAINT `fk_Cliente_Usuario10`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Cliente_Usuario1_idx` ON `cliente` (`Usuario_idUsuario` ASC);


-- -----------------------------------------------------
-- Table `Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `produto` (
  `idProduto` INT NOT NULL AUTO_INCREMENT,
  `descNome` VARCHAR(60) NOT NULL COMMENT 'Nome do produto',
  `descCoberturas` TEXT NULL COMMENT 'Coberturas do produto',
  `flgAplicativo` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '0 - Não exibe no aplicativo\n1 - Exibe no aplicativo\n',
  PRIMARY KEY (`idProduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProdutoVendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `produtoVendedor` (
  `Produto_idProduto` INT NOT NULL,
  `Vendedor_idVendedor` INT NOT NULL,
  `vrPreco` FLOAT NOT NULL COMMENT 'Preço de venda do produto para o vendedor',
  PRIMARY KEY (`Produto_idProduto`, `Vendedor_idVendedor`),
  CONSTRAINT `fk_Produto_has_Vendedor_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_has_Vendedor_Vendedor1`
    FOREIGN KEY (`Vendedor_idVendedor`)
    REFERENCES `vendedor` (`idVendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Produto_has_Vendedor_Vendedor1_idx` ON `produtoVendedor` (`Vendedor_idVendedor` ASC);

CREATE INDEX `fk_Produto_has_Vendedor_Produto1_idx` ON `produtoVendedor` (`Produto_idProduto` ASC);


-- -----------------------------------------------------
-- Table `Servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `servico` (
  `idServico` INT NOT NULL AUTO_INCREMENT,
  `dataVenda` DATE NULL,
  `dataVencimento` DATE NULL,
  `vrPreco` FLOAT NOT NULL COMMENT 'Valor da venda',
  `Produto_idProduto` INT NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idServico`),
  CONSTRAINT `fk_Venda_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venda_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Venda_Produto1_idx` ON `servico` (`Produto_idProduto` ASC);

CREATE INDEX `fk_Venda_Cliente1_idx` ON `servico` (`Cliente_idCliente` ASC);


-- -----------------------------------------------------
-- Table `VendaVendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vendaVendedor` (
  `Venda_idVenda` INT NOT NULL,
  `Vendedor_idVendedor` INT NOT NULL,
  `numComissao` INT NOT NULL DEFAULT '0' COMMENT 'Comissao da venda em %',
  PRIMARY KEY (`Venda_idVenda`, `Vendedor_idVendedor`),
  CONSTRAINT `fk_Venda_has_Vendedor_Venda1`
    FOREIGN KEY (`Venda_idVenda`)
    REFERENCES `servico` (`idServico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venda_has_Vendedor_Vendedor1`
    FOREIGN KEY (`Vendedor_idVendedor`)
    REFERENCES `vendedor` (`idVendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Venda_has_Vendedor_Vendedor1_idx` ON `vendaVendedor` (`Vendedor_idVendedor` ASC);

CREATE INDEX `fk_Venda_has_Vendedor_Venda1_idx` ON `vendaVendedor` (`Venda_idVenda` ASC);


-- -----------------------------------------------------
-- Table `Cobranca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cobranca` (
  `idCobranca` INT NOT NULL AUTO_INCREMENT,
  `dataGerado` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `dataPagamento` DATE NULL,
  `dataVencimento` DATE NOT NULL,
  `vrPreco` FLOAT NOT NULL,
  `flgPago` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '0 -À pagar\n1 - Pago',
  `Cliente_idCliente` INT NOT NULL,
  `Servico_idServico` INT NOT NULL,
  PRIMARY KEY (`idCobranca`),
  CONSTRAINT `fk_Cobranca_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cobranca_Servico1`
    FOREIGN KEY (`Servico_idServico`)
    REFERENCES `servico` (`idServico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Cobranca_Cliente1_idx` ON `cobranca` (`Cliente_idCliente` ASC);

CREATE INDEX `fk_Cobranca_Servico1_idx` ON `cobranca` (`Servico_idServico` ASC);


-- -----------------------------------------------------
-- Table `Comissao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comissao` (
  `idComissao` INT NOT NULL AUTO_INCREMENT,
  `dataGerado` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `vrComissao` FLOAT NOT NULL COMMENT 'Valor da comissão',
  `flgPago` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '0 - Não\n1 - Sim',
  `Vendedor_idVendedor` INT NOT NULL,
  `Servico_idServico` INT NOT NULL,
  PRIMARY KEY (`idComissao`),
  CONSTRAINT `fk_Comissao_Vendedor1`
    FOREIGN KEY (`Vendedor_idVendedor`)
    REFERENCES `vendedor` (`idVendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comissao_Servico1`
    FOREIGN KEY (`Servico_idServico`)
    REFERENCES `servico` (`idServico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Comissao_Vendedor1_idx` ON `comissao` (`Vendedor_idVendedor` ASC);

CREATE INDEX `fk_Comissao_Servico1_idx` ON `comissao` (`Servico_idServico` ASC);


-- -----------------------------------------------------
-- Table `Boleto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boleto` (
  `idBoleto` INT NOT NULL AUTO_INCREMENT,
  `dataGerado` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `dataVencimento` DATE NOT NULL,
  `flgCancelado` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '0 - Ativo\n1 - Cancelado',
  `Cobranca_idCobranca` INT NOT NULL,
  PRIMARY KEY (`idBoleto`),
  CONSTRAINT `fk_Boleto_Cobranca1`
    FOREIGN KEY (`Cobranca_idCobranca`)
    REFERENCES `cobranca` (`idCobranca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Boleto_Cobranca1_idx` ON `boleto` (`Cobranca_idCobranca` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


/*luan*/
ALTER TABLE `produtoVendedor` ADD `vrComissao` FLOAT NULL COMMENT 'Comissao do vendedor ao vender o produto';


ALTER TABLE usuario
	ADD CONSTRAINT uc_Email UNIQUE (descEmail);

ALTER TABLE `produtoVendedor`
  DROP PRIMARY KEY;
ALTER TABLE `produtoVendedor` ADD `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT FIRST, ADD PRIMARY KEY (`id`);
/*
tabela "ProdutoVendedor" removi a chave primaria da coluna "Produto_idProduto"*/

ALTER TABLE `cliente` CHANGE `flgPeriodicidadePagamento` `flgPeriodicidadePagamento` TINYINT(1) NULL DEFAULT '1' COMMENT '1 - Mensal2 - Anual';
ALTER TABLE `cliente` CHANGE `flgFormaPagamento` `flgFormaPagamento` TINYINT(1) NULL DEFAULT '2' COMMENT '1 - Pagseguro2 - Boleto Paghiper';
ALTER TABLE `usuario` CHANGE `Endereco_idEndereco` `Endereco_idEndereco` INT(11) NULL;

CREATE TABLE `formasPagamento` ( `id` INT NOT NULL AUTO_INCREMENT , `nome` VARCHAR(200) NOT NULL , `operadora` VARCHAR(200) NULL DEFAULT NULL , `email` VARCHAR(200) NULL DEFAULT NULL , `token` VARCHAR(200) NULL DEFAULT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB CHARSET=utf8 COLLATE utf8_general_ci;
/*luan*/


/*troca de todos os precos para double por causa da limitacao do float*/
ALTER TABLE `cobranca` CHANGE `vrPreco` `vrPreco` DOUBLE NOT NULL;
ALTER TABLE `produtoVendedor` CHANGE `vrPreco` `vrPreco` DOUBLE NOT NULL COMMENT 'Preço de venda do produto para o vendedor';
ALTER TABLE `servico` CHANGE `vrPreco` `vrPreco` DOUBLE NOT NULL COMMENT 'Valor da venda';

ALTER TABLE `comissao` ADD `flgTipoComissao` INT NOT NULL DEFAULT '1' COMMENT '0 - Comissao Recorrente /n 1 - Primeira Comissao' AFTER `flgPago`;


ALTER TABLE `cobranca` ADD `descRazaoCancelamento` TEXT NULL COMMENT 'Motivo do cancelamento da cobranca' AFTER `dataVencimento`;
ALTER TABLE `cobranca` ADD `flgCancelado` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '0 - Nao cancelada\n1 - Cancelada' AFTER `flgPago`;

ALTER TABLE `usuario` CHANGE `numTelefone` `numTelefone` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Telefone fixo (sem formatação)', CHANGE `numWhatsapp` `numWhatsapp` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Telefone Whatsapp (sem formatação)';


ALTER TABLE `servico` ADD `descBoletoPaghiper` TEXT NULL AFTER `dataVencimento`;
ALTER TABLE `servico` ADD `descPagseguro` TEXT NULL AFTER `descBoletoPaghiper`;

CREATE TABLE `soma`.`planosPagseguro` ( `id` INT NOT NULL AUTO_INCREMENT , `nome` TEXT NOT NULL , `code` TEXT NOT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;

CREATE TABLE `soma`.`periodicidade` ( `id` INT NOT NULL AUTO_INCREMENT , `periodo` TEXT NOT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;
INSERT INTO `periodicidade` (`id`, `periodo`) VALUES (NULL, 'Mensal');
INSERT INTO `periodicidade` (`id`, `periodo`) VALUES (NULL, 'Anual');

ALTER TABLE `planosPagseguro` ADD `idPeriodicidade` INT NOT NULL AFTER `code`;
ALTER TABLE planosPagseguro
    ADD CONSTRAINT fk_foreign_id_periodicidade
    FOREIGN KEY (idPeriodicidade)
    REFERENCES periodicidade(id);

CREATE TABLE `soma`.`produtoplano` ( `id` INT NOT NULL AUTO_INCREMENT , `idPlanoPagseguro` INT NOT NULL , `idProduto` INT NOT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;
ALTER TABLE `produtoplano` CHANGE `idPlanoPagseguro` `idPlanoPagseguro` INT(11) NULL;

ALTER TABLE produtoplano	
    ADD CONSTRAINT fk_foreign_id_planoPagseguro
    FOREIGN KEY (idPlanoPagseguro)
    REFERENCES planospagseguro(id);
ALTER TABLE produtoplano	
    ADD CONSTRAINT fk_foreign_id_produto
    FOREIGN KEY (idProduto)
    REFERENCES produto(idProduto);

ALTER TABLE `usuario` CHANGE `numCpf` `numCpf` BIGINT(13) NOT NULL COMMENT 'CPF (sem formatação)';

ALTER TABLE `Vendedor` ADD `descNomeBanca` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT 'Coluna para guardar o nome da banca' AFTER `flgBanca`;